version: 2
updates:
- package-ecosystem: "github-actions"
  directory: "/"
  schedule:
    interval: daily
  groups:
    action-dependencies:
      patterns:
        - "*"
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "03:00"
  groups:
    npm-dependencies:
      patterns:
        - "@angular*"
        - "@ngrx*"
        - "*eslint*"
        - "*"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: snyk
    versions:
    - 1.439.3
    - 1.440.1
    - 1.440.4
    - 1.440.5
    - 1.445.0
    - 1.446.0
    - 1.447.0
    - 1.448.0
    - 1.450.0
    - 1.452.0
    - 1.455.0
    - 1.456.0
    - 1.457.0
    - 1.459.0
    - 1.460.0
    - 1.462.0
    - 1.463.0
    - 1.464.0
    - 1.467.0
    - 1.471.0
    - 1.473.0
    - 1.474.0
    - 1.476.0
    - 1.478.0
    - 1.483.0
    - 1.486.0
    - 1.489.0
    - 1.491.0
    - 1.493.0
    - 1.495.0
    - 1.500.0
    - 1.503.0
    - 1.504.0
    - 1.505.0
    - 1.508.0
    - 1.509.0
    - 1.511.0
    - 1.514.0
    - 1.517.0
    - 1.518.0
    - 1.521.0
    - 1.522.0
    - 1.526.0
    - 1.527.0
    - 1.528.0
    - 1.529.0
    - 1.530.0
    - 1.531.0
    - 1.532.0
    - 1.538.0
    - 1.541.0
    - 1.557.0
    - 1.563.0
    - 1.564.0
    - 1.566.0
    - 1.570.0
  - dependency-name: "@typescript-eslint/eslint-plugin"
    versions:
    - 4.18.0
    - 4.19.0
    - 4.20.0
    - 4.21.0
  - dependency-name: tslib
    versions:
    - 2.2.0
  - dependency-name: "@typescript-eslint/parser"
    versions:
    - 4.18.0
    - 4.19.0
    - 4.20.0
    - 4.21.0
  - dependency-name: "@angular/cli"
    versions:
    - 11.1.2
    - 11.1.3
    - 11.1.4
    - 11.2.0
    - 11.2.1
    - 11.2.10
    - 11.2.2
    - 11.2.3
    - 11.2.4
    - 11.2.6
    - 11.2.7
    - 11.2.8
    - 11.2.9
  - dependency-name: "@angular/language-service"
    versions:
    - 11.1.1
    - 11.1.2
    - 11.2.0
    - 11.2.1
    - 11.2.10
    - 11.2.11
    - 11.2.2
    - 11.2.3
    - 11.2.4
    - 11.2.5
    - 11.2.7
    - 11.2.8
    - 11.2.9
  - dependency-name: karma
    versions:
    - 6.0.3
    - 6.0.4
    - 6.1.0
    - 6.1.2
    - 6.2.0
    - 6.3.0
    - 6.3.1
    - 6.3.2
  - dependency-name: rxjs
    versions:
    - 6.6.6
    - 6.6.7
  - dependency-name: "@types/node"
    versions:
    - 14.14.24
    - 14.14.25
    - 14.14.26
    - 14.14.27
    - 14.14.28
    - 14.14.30
    - 14.14.32
    - 14.14.33
    - 14.14.36
    - 15.0.0
  - dependency-name: "@types/jasmine"
    versions:
    - 3.6.6
    - 3.6.7
    - 3.6.8
  - dependency-name: "@angular-devkit/build-angular"
    versions:
    - 0.1101.2
    - 0.1101.3
    - 0.1101.4
    - 0.1102.0
    - 0.1102.1
    - 0.1102.10
    - 0.1102.2
    - 0.1102.3
    - 0.1102.4
    - 0.1102.6
    - 0.1102.7
    - 0.1102.8
    - 0.1102.9
  - dependency-name: jasmine-core
    versions:
    - 3.7.0
    - 3.7.1
  - dependency-name: "@angular-eslint/template-parser"
    versions:
    - 2.0.2
    - 2.1.0
    - 4.0.0
  - dependency-name: "@angular-eslint/eslint-plugin"
    versions:
    - 2.0.1
    - 2.0.2
    - 2.1.0
    - 4.0.0
  - dependency-name: "@angular-eslint/eslint-plugin-template"
    versions:
    - 2.0.1
    - 2.0.2
    - 2.1.0
    - 4.0.0
  - dependency-name: "@angular-eslint/schematics"
    versions:
    - 2.0.1
    - 2.0.2
  - dependency-name: eslint
    versions:
    - 7.22.0
    - 7.24.0
  - dependency-name: stylelint
    versions:
    - 13.10.0
    - 13.11.0
    - 13.12.0
  - dependency-name: zone.js
    versions:
    - 0.11.4
  - dependency-name: typescript
    versions:
    - 4.1.4
    - 4.1.5
  - dependency-name: stylelint-config-sass-guidelines
    versions:
    - 8.0.0
  - dependency-name: ngrx-store-localstorage
    versions:
    - 11.0.0
  - dependency-name: stylelint-scss
    versions:
    - 3.19.0
  - dependency-name: eslint-plugin-jsdoc
    versions:
    - 32.3.2
  - dependency-name: "@angular-eslint/builder"
    versions:
    - 2.1.0
    - 4.0.0
  - dependency-name: jasmine-spec-reporter
    versions:
    - 7.0.0
  - dependency-name: eslint-plugin-ngrx
    versions:
    - 1.17.4
- package-ecosystem: docker
  directory: "/"
  schedule:
    interval: daily
    time: "03:00"
  groups:
    docker-dependencies:
      patterns:
        - "*"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: node
    versions:
    - 15.10.0
    - 15.11.0
    - 15.12.0
    - 15.13.0
    - 15.14.0
    - 15.7.0
    - 15.8.0
    - 15.9.0
