# GitHub Actions docs
# https://help.github.com/en/articles/about-github-actions
# https://help.github.com/en/articles/workflow-syntax-for-github-actions
name: CI

on:
  # Trigger the workflow on push or pull request,
  # but only for the master branch
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  lint:
    name: Lint application code
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1

      - name: Use Node.js 13.7
        uses: actions/setup-node@v1
        with:
          node-version: 13.7

      - name: Install dependencies
        run: yarn install

      - name: Run `yarn lint`
        run: yarn lint

  lint-markdown:
    name: Lint application markdown files
    runs-on: ubuntu-lates

    steps:
      - uses: actions/checkout@v1

      - name: Lint `README.md`
        uses: avto-dev/markdown-lint@v1
        with:
          config: '/markdown-lint.yml'
          args: './README.md'
